package com.ironhack.enums;

public enum CommandType {
    CREATE_LEAD,
    SHOW_LEADS,
    SHOW_CONTACTS,
    SHOW_OPPORTUNITIES,
    SHOW_ACCOUNTS,
    CONVERT,
    LOOKUP_LEAD,
    CLOSE_LOST,
    CLOSE_WON,
    NEW_LEAD,
    LOOKUP_LEAD_ID,
    LOOKUP_CONTACT_ID,
    LOOKUP_OPPORTUNITY_ID,
    LOOKUP_ACCOUNT_ID,
    CONVERT_LEAD,
    EXIT,
    HELP
}

